#!/bin/bash

CMD=${0##*/}
DIR=${0%/*}

. $DIR/TEST_COMMON


# Running the tests from their directory, gives nice short names.
cd $DIR

usage() {
    echo "$CMD [-O<level>] [-h] [files]*"
    echo "    -O <level>    opimization level"
    echo "    -h            output this message"

    exit 1
}

declare TEMP
TEMP=$(getopt -o "hO:" \
    -n "$CMD" -- "$@")
if [[ $? -ne 0 ]]; then usage > /dev/stderr; fi
eval set -- "$TEMP"
unset TEMP

typeset optim

while true
do
    case "$1" in
        -O)      optim=-O$2;                          shift 2 ;;
        -h) usage                                           ;;
        --) shift
            break
            ;;
        *) echo Internal Error "'$1'"; exit 1   ;;
    esac
done

CASTRO_FLAGS="$optim --nohelperload"

Main() {
    run_all "$@"
}

#
# current_test global
#
run_all() {
    for t in "$@"
    do
        current_test=${t%.castro}
        echo "current_test: $current_test"
        gen $t
    done
}

gen() {
    tcastro $CASTRO_FLAGS $current_test.castro 2> $current_test.stderr
    make_gold
}

make_gold() {
    mv_gold as def
    if [[ -e $current_test.helper.castro ]]
    then
        mv_gold helper.castro helper.as helper.def
    fi
    if [[ -e $current_test.map ]]
    then
        mv_gold map
    else
        echo "    NOTE: no $current_test.map file"
    fi
    mv_gold stderr
}

mv_gold() {
    local ext
    for ext in $*
    do
        mv $current_test.$ext gold/$current_test.$ext-gold
    done
}

Main "$@"
