#!/bin/bash

CMD=${0##*/}
DIR=${0%/*}

. $DIR/TEST_COMMON


# Running the tests from their directory, gives nice short names.
cd $DIR

Main() {
    run_all "$@"
}

#
# current_test global
#
run_all() {
    for t in "$@"
    do
        current_test=${t%.castro}
        echo "current_test: $current_test"
        gen $t
    done
}

gen() {
    tcastro --nostartup $current_test.castro 2> $current_test.stderr
    make_gold
}

make_gold() {
    mv_gold as def
    if [[ -e $current_test.helper.castro ]]
    then
        mv_gold helper.castro helper.as helper.def
    fi
    if [[ -e $current_test.map ]]
    then
        mv_gold map
    else
        echo "    NOTE: no $current_test.map file"
    fi
    mv_gold stderr
}

mv_gold() {
    local ext
    for ext in $*
    do
        mv $current_test.$ext gold/$current_test.$ext-gold
    done
}

Main "$@"
