// This file is generated by a script: scipts/extract_constants
// from astrolog's data.cpp which is copyrighted by:
// Walter D. Pullen (Astara@msn.com, http://www.astrolog.org/astrolog.htm)

package com.raelity.astrolog.castro.tables;

public class AstrologConstants
{
private AstrologConstants() { }


public static final String szSignName[] = {"",
  "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
  "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"};
public static final String szObjName[] = {
  "Earth", "Sun", "Moon", "Mercury", "Venus", "Mars",       // Planets
  "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto",
  "Chiron", "Ceres", "Pallas", "Juno", "Vesta",             // Asteroids
  "North Node", "South Node",                               // Nodes
  "Lilith", "Fortune", "Vertex", "East Point",              // Others
  "Ascendant", "2nd Cusp", "3rd Cusp", "Nadir",             // Cusps
  "5th Cusp", "6th Cusp", "Descendant", "8th Cusp",
  "9th Cusp", "Midheaven", "11th Cusp", "12th Cusp",
  "Vulcan", "Cupido", "Hades", "Zeus", "Kronos",            // Uranians
  "Apollon", "Admetos", "Vulkanus", "Poseidon",
  "Hygiea", "Pholus", "Eris", "Haumea", "Makemake",         // Dwarfs
  "Gonggong", "Quaoar", "Sedna", "Orcus",

  "Phobos", "Deimos",                                       // Moons
  "Ganymede", "Callisto", "Io", "Europa",
  "Titan", "Rhea", "Iapetus", "Dione",
  "Tethys", "Enceladus", "Mimas", "Hyperion",
  "Titania", "Oberon", "Umbriel", "Ariel", "Miranda",
  "Triton", "Proteus", "Nereid",
  "Charon", "Hydra", "Nix", "Kerberos", "Styx",
  "JupCOB", "SatCOB", "UraCOB", "NepCOB", "PluCOB",

  "Sirius", "Canopus", "Rigil Kent.", "Arcturus", "Vega",   // Stars
  "Capella", "Rigel", "Procyon", "Betelgeuse", "Achernar",
  "Agena", "Altair", "Acrux", "Aldebaran", "Antares",
  "Spica", "Pollux", "Fomalhaut", "Deneb", "Becrux",
  "Regulus", "Adara", "Castor", "Shaula", "Bellatrix",
  "Gacrux", "Alnath", "Alnilam", "Miaplacidus", "Alnair",
  "Alioth", "Dubhe", "Wezen", "Kaus Austr.", "Alkaid",
  "Sargas", "Menkalinan", "Peacock", "Alhena", "Avior",
  "Murzim", "Alphard", "Polaris", "Algol", "Suhail",
  "Alcyone", "Andromeda", "Zeta Retic.", "Galactic C.", "Great Attr.",

  "1st Cusp", "4th Cusp", "7th Cusp", "10th Cusp"};         // Extra
public static final String rgObjName[] = {"Node" /*oNod*/, "Nod:" /*oNod*/,
  "Rahu" /*oNod*/, "Ketu" /*oSou*/,
  "M.C." /*oMC*/, "I.C." /*oNad*/,
  "1st" /*oAsc*/, "4th" /*oNad*/, "7th" /*oDes*/, "10th" /*oMC*/,
  "Vulcanus" /*oVlk*/,
  "Star" /*starLo*/, "Orion" /*oOri*/, "Pleiades" /*oPle*/, "M31" /*oAnd*/,
  "Milky Way" /*oGal*/, "" /*-1*/};
public static final String szSystem[] = {
  "Placidus", "Koch", "Equal", "Campanus", "Meridian", "Regiomontanus",
  "Porphyry", "Morinus", "Topocentric", "Alcabitius", "Krusinski",
  "Equal (MC)", "Pullen (S.Ratio)", "Pullen (S.Delta)", "Whole", "Vedic",
  "Sripati", "Horizon", "APC", "Carter P.Equat.", "Sunshine", "Savard-A",
  "Null",
  "Whole (MC)", "Vedic (MC)",
  "Equal (Balanced)", "Whole (Balanced)", "Vedic (Balanced)",
  "Equal (EP)", "Whole (EP)", "Vedic (EP)",
  "Equal (Vertex)", "Whole (Vertex)", "Vedic (Vertex)",
  "Porphyry (EP)", "Porphyry (Vertex)", "Pullen (SR, EP)",
  "Pullen (SR, Vertex)", "Pullen (SD, EP)", "Pullen (SD, Vertex)"};
public static final String rgSystem[] = {"E-Asc" /*hsEqual*/, "E-MC" /*hsEqualMC*/,
  "P-SR" /*hsSineRatio*/, "P-SD" /*hsSineDelta*/,
  "Ratio" /*hsSineRatio*/, "Delta" /*hsSineDelta*/,
  "S-Ratio" /*hsSineRatio*/, "S-Delta" /*hsSineDelta*/,
  "Albategnius" /*hsSavardA*/, "Albategnus" /*hsSavardA*/,
  "W-Asc" /*hsWhole*/, "V-Asc" /*hsVedic*/,
  "W-MC" /*hsWholeMC*/, "V-MC" /*hsVedicMC*/, "E-Bal" /*hsEqualBalanced*/,
  "W-Bal" /*hsWholeBalanced*/, "V-Bal" /*hsVedicBalanced*/,
  "E-EP" /*hsEqualEP*/, "W-EP" /*hsWholeEP*/, "V-EP" /*hsVedicEP*/,
  "E-Ver" /*hsEqualVertex*/, "W-Ver" /*hsWholeVertex*/, "V-Ver" /*hsVedicVertex*/,
  "P-EP" /*hsPorphyryEP*/, "P-Ver" /*hsPorphyryVtx*/,
  "SR-EP" /*hsSineRatioEP*/, "SR-Ver" /*hsSineRatioVtx*/,
  "SD-EP" /*hsSineDeltaEP*/, "SD-Ver" /*hsSineDeltaVtx*/, "" /*-1*/};
public static final String szAspectName[] = {"",
  "Conjunct", "Opposite", "Square", "Trine", "Sextile",
  "Inconjunct", "SemiSextile", "SemiSquare", "SesquiQuadrate",
  "Quintile", "BiQuintile",
  "SemiQuintile", "Septile", "Novile",
  "BiNovile", "BiSeptile", "TriSeptile", "QuatroNovile",
  "TreDecile",
  "Undecile", "BiUndecile", "TriUndecile", "QuatroUndecile", "QuintUndecile",
  "Parallel", "ContraParallel"};
public static final String rgAspectName[] =
  {"Quincunx" /*aInc*/, "Octile" /*aSSq*/, "" /*-1*/};
public static final String szAspectAbbrev[] = {"",
  "Con", "Opp", "Squ", "Tri", "Sex",
  "Inc", "SSx", "SSq", "Ses", "Qui", "BQn",
  "SQn", "Sep", "Nov", "BNv", "BSp", "TSp", "QNv",
  "TDc", "Un1", "Un2", "Un3", "Un4", "Un5",
  "Par", "CPr"};
public static final String szMonth[] = {"",
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"};
public static final String szDay[] = {"Sunday", "Monday", "Tuesday", "Wednesday",
  "Thursday", "Friday", "Saturday"};

}
